---
apiVersion: v1
kind: Service
metadata:
  name: dash
  namespace: {{ .Release.Namespace }}
  labels:
    app: dash
    suite: {{ template "fullname" . }}
spec:
  ports:
  - name: dash-http
    {{- if eq .Values.dash.service.type "NodePort" }}
    nodePort: 30080
    {{- end }}
    port: 8080
  - name: grpc-proxy-http
    {{- if eq .Values.dash.service.type "NodePort" }}
    nodePort: 30081
    {{- end }}
    port: 8081
  selector:
    app: dash
    suite: {{ template "fullname" . }}
  type: {{ .Values.dash.service.type }}