{{- if .Values.gceProxy }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "metabase.fullname" . }}-cloudsql-instance-credentials
  labels:
    app: {{ template "metabase.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  credentials.json: {{ .Files.Get "config1.toml" | b64enc }}
{{- end }}
